// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-FpIYIZuOdCxi_HPM833qhDMY9JzLjpI',
    appId: '1:1011057604731:web:a03f9a29b8fce75e610ade',
    messagingSenderId: '1011057604731',
    projectId: 'justus-c98bf',
    authDomain: 'justus-c98bf.firebaseapp.com',
    storageBucket: 'justus-c98bf.firebasestorage.app',
    measurementId: 'G-9K8MGG7CVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdYD38dwm7Javabp3HE0EyTfs-QpJobBg',
    appId: '1:1011057604731:android:30dfcc68db7fd5e6610ade',
    messagingSenderId: '1011057604731',
    projectId: 'justus-c98bf',
    storageBucket: 'justus-c98bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiy8X2lMb3y-56_xXzlxpPQ_wfCzxwAo8',
    appId: '1:1011057604731:ios:309ba156a2daab2c610ade',
    messagingSenderId: '1011057604731',
    projectId: 'justus-c98bf',
    storageBucket: 'justus-c98bf.firebasestorage.app',
    iosBundleId: 'com.antigravity.justus.justUs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiy8X2lMb3y-56_xXzlxpPQ_wfCzxwAo8',
    appId: '1:1011057604731:ios:309ba156a2daab2c610ade',
    messagingSenderId: '1011057604731',
    projectId: 'justus-c98bf',
    storageBucket: 'justus-c98bf.firebasestorage.app',
    iosBundleId: 'com.antigravity.justus.justUs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-FpIYIZuOdCxi_HPM833qhDMY9JzLjpI',
    appId: '1:1011057604731:web:e70e78b32a4e247b610ade',
    messagingSenderId: '1011057604731',
    projectId: 'justus-c98bf',
    authDomain: 'justus-c98bf.firebaseapp.com',
    storageBucket: 'justus-c98bf.firebasestorage.app',
    measurementId: 'G-C5FT07E0DK',
  );
}
