import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'core/theme/app_theme.dart';
import 'core/router/app_router.dart';
import 'core/services/storage_service.dart';
import 'package:firebase_core/firebase_core.dart';
// import 'package:just_us/firebase_options.dart'; // This file is generated by flutterfire configure

import 'data/providers/locale_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await StorageService.init();

  try {
    // Note: You must run 'flutterfire configure' to generate firebase_options.dart
    // and then uncomment the lines below to enable live chat features.
    /*
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    */
    print("Firebase initialization skipped. Run 'flutterfire configure' to enable.");
  } catch (e) {
    print("Firebase initialization failed: $e");
  }

  runApp(const ProviderScope(child: JustUsApp()));
}

class JustUsApp extends ConsumerWidget {
  const JustUsApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final locale = ref.watch(localeProvider);

    return MaterialApp.router(
      title: 'Just Us',
      theme: AppTheme.darkTheme,
      routerConfig: appRouter,
      locale: locale,
      debugShowCheckedModeBanner: false,
    );
  }
}
